FROM node:20 as build
WORKDIR /app
COPY package*.json ./

RUN npm install
COPY . .
RUN npm run build


FROM nginx:latest

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx_react.conf
#
EXPOSE 3000

CMD ["nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx_react.conf"]

