FROM nginx:latest

RUN apt-get update && apt-get install -y certbot

COPY nginx.conf /etc/nginx/nginx.conf

# COPY ./dist /usr/share/nginx/html


EXPOSE 80
EXPOSE 443

# CMD [ "nginx", "-g", "daemon off;" ]
#