FROM nginx:latest

RUN apk add --no-cache certbot

COPY nginx.conf /etc/nginx/nginx.conf

# COPY ./dist /usr/share/nginx/html

USER www-data


EXPOSE 80
EXPOSE 443

# CMD [ "nginx", "-g", "daemon off;" ]
#