FROM ramsrib/pgvector:12

COPY init.sql /docker-entrypoint-initdb.d/init.sql

# CMD [ "/bin/sh", "-c", "psql","-U", "$POSTGRES_USER", "-d", "$POSTGRES_DB", "-f", "/docker-entrypoint-initdb.d/init.sql" ]

# CMD /bin/sh -c psql -U $POSTGRES_USER -d $POSTGRES_DB -f /docker-entrypoint-initdb.d/init.sql
