-- public.case_entity definition
CREATE TABLE IF NOT EXISTS public.case_entity (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	summary varchar(255) NULL,
	CONSTRAINT case_entity_pkey PRIMARY KEY (id)
);


-- public.email_verification_entity definition
CREATE TABLE IF NOT EXISTS public.email_verification_entity (
	id bigserial NOT NULL,
	code varchar(255) NULL,
	email varchar(255) NULL,
	expiry_date timestamp(6) NULL,
	verified bool NOT NULL,
	CONSTRAINT email_verification_entity_pkey PRIMARY KEY (id)
);


-- public.lawyer_entity definition
CREATE TABLE IF NOT EXISTS public.lawyer_entity (
	lawyer_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	description varchar(255) NULL,
	expertise_main varchar(255) NULL,
	office_location varchar(255) NULL,
	phone_number varchar(255) NULL,
	point int4 NULL,
	qualification varchar(255) NULL,
	user_id int8 NULL,
	CONSTRAINT lawyer_entity_pkey PRIMARY KEY (lawyer_id),
	CONSTRAINT uk5g7djqkkxckwlcj6e0b5kv5ud UNIQUE (user_id)
);


-- public.lawyer_entity foreign keys
ALTER TABLE public.lawyer_entity ADD CONSTRAINT fkqrda6olgg11gtvjhnle7ejddw FOREIGN KEY (user_id) REFERENCES public.user_entity(id);


-- public.lawyer_expertise_sub definition
CREATE TABLE IF NOT EXISTS public.lawyer_expertise_sub (
	lawyer_id int8 NOT NULL,
	expertise_sub varchar(255) NULL
);


-- public.lawyer_expertise_sub foreign keys
ALTER TABLE public.lawyer_expertise_sub ADD CONSTRAINT fkojoj8jiicbg16nxs2ryi8yexf FOREIGN KEY (lawyer_id) REFERENCES public.lawyer_entity(lawyer_id);


-- public.user_entity definition
CREATE TABLE IF NOT EXISTS public.user_entity (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_date timestamp(6) NULL,
	email varchar(255) NULL,
	email_token varchar(255) NULL,
	is_email_verified bool NULL,
	is_first bool NULL,
	nickname varchar(255) NULL,
	"password" varchar(255) NULL,
	profile_img varchar(255) NULL,
	update_date timestamp(6) NULL,
	user_type varchar(255) NULL,
	CONSTRAINT user_entity_pkey PRIMARY KEY (id)
);


-- public.user_entity_interests definition
CREATE TABLE IF NOT EXISTS public.user_entity_interests (
	user_entity_id int8 NOT NULL,
	interests varchar(255) NULL
);


-- public.user_entity_interests foreign keys
ALTER TABLE public.user_entity_interests ADD CONSTRAINT fkki0fg4fix963sxaci9frl4w4w FOREIGN KEY (user_entity_id) REFERENCES public.user_entity(id);


-- public.user_subscriptions definition
CREATE TABLE IF NOT EXISTS public.user_subscriptions (
	user_id int8 NOT NULL,
	subscriptions varchar(255) NULL
);


-- public.user_subscriptions foreign keys
ALTER TABLE public.user_subscriptions ADD CONSTRAINT fkjvvc0uxv5svod2n9ovcnmsi44 FOREIGN KEY (user_id) REFERENCES public.user_entity(id);


-- public.verification_token_entity definition
CREATE TABLE IF NOT EXISTS public.verification_token_entity (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	expiry_date timestamp(6) NULL,
	"token" varchar(255) NULL,
	user_id int8 NOT NULL,
	CONSTRAINT verification_token_entity_pkey PRIMARY KEY (id)
);


-- public.verification_token_entity foreign keys

ALTER TABLE public.verification_token_entity ADD CONSTRAINT fk1llgpobomks3q7t6qwqtd17ef FOREIGN KEY (user_id) REFERENCES public.user_entity(id);

CREATE TABLE IF NOT EXISTS public.law_info (
	rule_id serial4 NOT NULL,
	law_id varchar(255) NULL,
	proclamation_date date NULL,
	proclamation_number varchar(255) NULL,
	"language" varchar(50) NULL,
	law_type varchar(255) NULL,
	law_name_kr varchar(255) NULL,
	law_name_ch varchar(255) NULL,
	law_short_name varchar(255) NULL,
	is_title_changed varchar(1) NULL,
	is_korean_law varchar(1) NULL,
	part_code varchar(50) NULL,
	related_department varchar(255) NULL,
	phone_number varchar(50) NULL,
	enforcement_date date NULL,
	revision_type varchar(50) NULL,
	is_annex_included varchar(1) NULL,
	is_proclaimed varchar(1) NULL,
	contact_department jsonb NULL,
	CONSTRAINT law_info_pkey PRIMARY KEY (rule_id)
);

CREATE TABLE IF NOT EXISTS public.law_sections (
	section_id serial4 NOT NULL,
	law_id varchar(255) NULL,
	part varchar(255) NULL,
	chapter varchar(255) NULL,
	"section" varchar(255) NULL,
	article varchar(255) NULL,
	clause varchar(255) NULL,
	"content" text NULL,
	CONSTRAINT law_sections_pkey PRIMARY KEY (section_id)
);