FROM amazoncorretto:17

WORKDIR /app

COPY gradlew* ./
COPY gradle/ gradle/

COPY build.gradle settings.gradle ./

RUN chmod +x ./gradlew

COPY src/ src/

# 지금 -x test로 테스트 건너뛰게 되있는데, 나중에 수정해야함
RUN ./gradlew build --no-daemon -x test

CMD ["java", "-jar", "build/libs/here-law.jar"]

EXPOSE 8080