FROM amazoncorretto:17
WORKDIR /app

COPY gradlew gradlew
COPY gradlew.bat gradlew.bat
COPY gradle/ gradle/

COPY build.gradle settings.gradle ./
COPY src/ src/

RUN ./gradlew build

CMD ["java", "-jar", "build/libs/myapp.jar"]

EXPOSE 8080