FROM python:3.10
WORKDIR /app

COPY requirements_ec2.txt .

RUN pip install --no-cache-dir -r requirements_ec2.txt
RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]