FROM python:3.10
WORKDIR /app

COPY requirements.txt .

RUN apt-get update && apt-get install -y \
    libreoffice \
    wget \
    unzip \
    fonts-nanum \
    --no-install-recommends

RUN pip install --no-cache-dir -r requirements.txt

RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

RUN wget https://github.com/naver/nanumfont/releases/download/v1.0/NanumFont_TTF_ALL.zip -O /tmp/NanumFont.zip && \
    unzip /tmp/NanumFont.zip -d /usr/share/fonts/truetype/nanum && \
    fc-cache -fv && \
    rm /tmp/NanumFont.zip

COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]